---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka
  namespace: flux-system
spec:
  interval: 15m
  releaseName: kafka
  targetNamespace: kafka
  chart:
    spec:
      chart: kafka
      version: 31.3.1
      sourceRef:
        kind: HelmRepository
        name: kafka
        namespace: helm-repositories
  valuesFrom:
    - kind: Secret
      name: kafka-values
